#!/usr/bin/env python
# coding: utf-8
# %%
import os
import torch
from transformers import Trainer, TrainingArguments, AutoTokenizer, AutoModelForTokenClassification 

# helper functions:
from tokenize_align import tokenize_n_align
from datasets import load_dataset

# %%
# check if GPU's available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# %%
# read data from multiple jsonl files and tokenize them
def data_preprocess(tokenizer, LANGS):
    
    # training data address:
    our_data = [f'./training_data/{lang}.jsonl' for lang in LANGS]  # data generated by ourselves
    print(f"Now training on data: {our_data}")
    
    # load training data contents
    dataset = load_dataset('json', data_files=our_data) 
    
    # remove unwanted columns from the 2 groups of data & concatenate them together
    relevant_columns = ['model_output_text', 'hard_labels']
    dataset = dataset.shuffle()  # shuffle the order of datapoints
    dataset = dataset["train"].remove_columns([col for col in dataset["train"].column_names if col not in relevant_columns])
    
    # tokenize the dataset
    tokenized_datasets = dataset.map(lambda x: tokenize_n_align(x, tokenizer), batched=True)
    
    # split into train and validation sets
    train_dataset, eval_dataset = tokenized_datasets.train_test_split(test_size=0.05).values()

    return train_dataset, eval_dataset

# 
def train(model_name, LANGS):

    # define labels & map labels to IDs for training
    labels = ["O", "I"]  # 'O' = outside span, 'I' = inside span
    label2id = {label: i for i, label in enumerate(labels)}
    id2label = {i: label for label, i in label2id.items()}

    # load tokenizer & model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForTokenClassification.from_pretrained(model_name, num_labels=len(labels)).to(device)
    model.config.id2label = id2label
    model.config.label2id = label2id

    #get data preprocessed
    train_dataset, eval_dataset = data_preprocess(tokenizer, LANGS)
    
    # define training epoch
    num_epochs = 10

    # set up the training argument & trainer
    training_args = TrainingArguments(
        output_dir = "./results",
        eval_strategy = "epoch",
        learning_rate = 2e-5,
        per_device_train_batch_size = 8,
        per_device_eval_batch_size = 8,
        num_train_epochs = num_epochs,
        weight_decay = 0.01,
        logging_dir = "./logs",
        logging_steps = 1,
        save_safetensors=False
    )
    
    trainer = Trainer(
        model = model,
        args = training_args,
        train_dataset = train_dataset,
        eval_dataset = eval_dataset,
        tokenizer = tokenizer
    )
    
    # start fine-tuning
    trainer.train()
    
    # save the fine-tuned model & tokenizer to the directory "models"
    model_name_stripped = model_name.split("/")[-1]     # extract the last part of the model's name --> remove "/" to prevent the fine-tuned model to be stored in a separate directory
    fine_tuned_model_path = f"../models/{model_name_stripped}-{str(num_epochs)}ep-M"

    model.save_pretrained(fine_tuned_model_path)
    tokenizer.save_pretrained(fine_tuned_model_path)

if __name__ == "__main__":
    # get training data's name & model name from the os
    LANGS = (os.getenv("LANGS", "en")).split()  # a list of languages the model will be fine-tuned on
    model_name = os.getenv("MODEL", "default") # base model's name

    # check if the 3 variables are loaded properly
    print(f"Raw LANGS from environment: {os.getenv('LANGS')}")
    print("----------------------------")
    print(f"LANGS: {LANGS}")
    print(f"model_name: {model_name}")
    print("----------------------------")
    
    # fine tune the base model
    train(model_name, LANGS)

