# -*- coding: utf-8 -*-
"""fine_tuned_model_v0.2(QA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHexQqBzrg5oLW14zVe233joYjid8I0a
"""

!pip install transformers datasets

import torch
import torch.nn.functional as F
from transformers import BertTokenizerFast, BertForTokenClassification, Trainer, TrainingArguments
from datasets import Dataset

"""# **1. Dataset Prep:**"""

# start experimenting with this model
model_name = "bert-base-cased"
# get tokenizer
tokenizer = BertTokenizerFast.from_pretrained(model_name)

# define labels & map labels to IDs for training
labels = ["O", "I"]  # 'O' = outside span, 'I' = inside span
label2id = {label: i for i, label in enumerate(labels)}
id2label = {i: label for label, i in label2id.items()}

# a toy training dataset (from the provided val set. just for testing! hange this afterwards!)
data = [
    {
        "model_input":"How many genera does the Erysiphales order contain?",
        "model_output_text":"The Elysiphale order contains 5 genera.",
        "hard_labels":[[30,31]]  # hallucination spans (start, end)
    },
    {
        "model_input":"What did Petra van Staveren win a gold medal for?",
        "model_output_text":"Petra van Stoveren won a silver medal in the 2008 Summer Olympics in Beijing, China.",
        "hard_labels":[[25,31],[45,49],[69,83]]
    }
]

# convert dataset to a Dataset object
dataset = Dataset.from_dict({
    "model_input": [d["model_input"] for d in data],
    "model_output_text": [d["model_output_text"] for d in data],
    "hard_labels": [d["hard_labels"] for d in data],
})

"""# Helper function: tokenize & align lables
--------------------------------------------------------
Tokenize Qestion-Answer pairs and these tokens with corresponding lables (I or O) based on the given sratring/ending position of hallucination.
--------------------------------------------------------

function input = dictionary {'model_input', 'model_output_text' , 'soft_labels'}
*   'model_input': question text
*   'model_output_text': answer text
*   'hard_labels': a list of lists, marking start & end of hallucination
--------------------------------------------------------

function output = dictionary {'input_ids', 'attention_mask', 'token_type_ids', 'labels'}
*   'input_ids': token ID
*   'attention_mask': marks padding
*   'token_type_ids': ignore question for labeling (0 or 1)
*   'labels': hallucination/not (1 or 0)
"""

# tokenize and align labels for multiple spans
def tokenize_n_align(examples):
    inputs = tokenizer(
        examples["model_input"],
        examples["model_output_text"],
        truncation=True,
        padding="max_length", # default = 512 tokens
        return_offsets_mapping=True
    )

    labels = []
    for i in range(len(inputs["input_ids"])):
        # Get offsets for the current tokenization
        offset_mapping = inputs['offset_mapping'][i]

        # Create a label array initialized to 'O'
        label_sequence = ['O'] * len(offset_mapping)

        # Iterate over each span in hard_labels
        for start_end in examples["hard_labels"][i]:
            start_char, end_char = start_end

            for j, (start, end) in enumerate(offset_mapping):
                # Check if the token spans any character in the answer span
                if start_char <= start < end_char or start < end_char <= end:
                    label_sequence[j] = 'I'

        labels.append([label2id[label] for label in label_sequence])

    # Add labels to the inputs
    inputs["labels"] = labels
    return inputs

# preprocess the dataset
train_dataset = dataset.map(tokenize_n_align, batched=True)

"""# **2. Model Set-up:**"""

# prepare the model
model = BertForTokenClassification.from_pretrained(model_name, num_labels=len(labels))
model.config.id2label = id2label
model.config.label2id = label2id

# set up the trainer
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=1,
    run_name = "qa_model"
)

# --------------------------------
# just for testing the code! change this afterwards!
eval_dataset = train_dataset
# --------------------------------

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer
)

# train the model (fine-tuning)
trainer.train()

# save the fine-tuned model & tokenizer
fine_tuned_model_path = "./qa_model"
model.save_pretrained(fine_tuned_model_path)
tokenizer.save_pretrained(fine_tuned_model_path)

"""# **3. Visualize output of the fine-tuned model**"""

# load the fine-tuned model & its tokenizer
new_model = BertForTokenClassification.from_pretrained(fine_tuned_model_path)
new_tokenizer = BertTokenizerFast.from_pretrained(fine_tuned_model_path)

# a test example (question & answer)
test_example = {
    "model_input": "Where is the University of Helsinki located?",
    "model_output_text": "The University of Helsinki is located in Helsinki, Finland."
}

# tokenize the example above
test_inputs = new_tokenizer(
    test_example["model_input"], # question
    test_example["model_output_text"], # answer
    truncation=True,  # split the text if it exceedes the maximum length
    padding="max_length",
    return_offsets_mapping=True, # offsets mapping = a list of (start, end), marking position of tokens in the original text
    return_tensors="pt" # return output as pyTorch tensor
)

# remove offset mappings before passing inputs to the model
offset_mapping = test_inputs.pop("offset_mapping")

# run the model & get the logits
with torch.no_grad():
    outputs = new_model(**test_inputs) # ** converts dict into argument ("key": val -> key = val)
logits = outputs.logits

# calculate probabilities of predicted labels using softmax
probs = F.softmax(logits, dim=-1)

# get predicted labels for each token using argmax
predicted_label_ids = logits.argmax(dim=-1).squeeze().tolist()  # dim = -1: appliy argmax function to the LAST dimension of the logits tensor, AKA the label indices
predicted_labels = [new_model.config.id2label[label_id] for label_id in predicted_label_ids] # map label ID to labels

# get the hallucination spans (tokens labeled as "I")
spans = []
current_span = []
current_probs = []

for label, (start, end), prob in zip(predicted_labels, offset_mapping.squeeze().tolist(), probs.squeeze()):

    # ignore special tokens' labels (e.g., [SEP], offsets with start & end as [0, 0])
    if start == 0 and end == 0:
        continue

    i_prob = prob[new_model.config.label2id["I"]].item()  # probability of label "I"

    if label == "I":
        if not current_span:
            current_span = [start, end]
            current_probs = [i_prob]
        else:
            # extend the current span to include the current token
            current_span[1] = end
            current_probs.append(i_prob)
    else:
        # end the current span when encountering an "O" label
        if current_span:
            average_prob = sum(current_probs) / len(current_probs)  # Calculate average probability for the span
            spans.append((current_span[0], average_prob, current_span[1]))
            current_span = []
            current_probs = []

# append remaining spans
if current_span:
    average_prob = sum(current_probs) / len(current_probs)
    spans.append((current_span[0], average_prob, current_span[1]))

# display the results
print("soft_labels:")
for start, prob, end in spans:
    span_text = test_example["model_output_text"][start:end]
    print(f"start: {start}, prob: {prob:.3f}, end: {end}, text: '{span_text}'")

"""# Inspecting the output contents:"""

# import numpy as np

# # decoded tokens (with special tokens like [SEP])
# input_ids = test_inputs['input_ids'][0]  # get the input IDs tensor
# decoded_tokens = [tokenizer.decode([id]) for id in input_ids if id != tokenizer.pad_token_id]

# # get tokens with "I" label
# np_pred_labels, np_tokens = np.array(predicted_labels), np.array(decoded_tokens)
# mask = (np_pred_labels == 'I')
# result = np_tokens[mask[:len(np_tokens)]]


# print("Decoded Tokens:", decoded_tokens)
# print("Predicted Labels:", predicted_labels) # "I" or "O" for each token (include padding!)
# print("Hallucinated Token ID:",[(i, label) for i, label in enumerate(predicted_labels) if label == "I"])
# print("Hallucinated Tokens:", result)
